source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "rails", "~> 7.1.0"
gem "bootsnap", require: false
gem "sqlite3", "~> 1.4"
gem "puma", ">= 5.0"
gem "image_processing", "~> 1.2"  # for cover thumbnails via Active Storage variants
gem "rack-cors"

group :development, :test do
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
  gem "faker"
  gem "rubocop", require: false
end

group :development do
  gem "listen"
end
